### ISSUE TITLE
为什么在server_main.c中屏蔽延时，浏览器与服务器connect后，浏览器与服务器立马断开

### ISSUE THREAD

**Issue by Qianxunha** [wexiangis/websocket_for_linux#2]
博主你好：
在server_main.c中：
for(i = 0; i < EPOLL_RESPOND_NUM; i++)
{
        if(wss.client_fd_array[i][1] != 0 && wss.client_fd_array[i][0] > 0)
	        {
	            client_fd = wss.client_fd_array[i][0];
	            if(webSocket_send(client_fd, buff, n, false, WDT_BINDATA) < 0)
                {
                    printf("server webSocket_send err !!\r\n");
                    exitFlag = 1;
                    break;
                }
	        }
	    }
	   // webSocket_delayms(1000);
}
屏蔽延时函数，浏览器与服务器connect后，浏览器与服务器立马断开
没有屏幕延时，connect后，浏览器与服务器不会断开

**Comment by wexiangis** [comment]
多谢反馈；
1、你说的问题已在最新提交里解决，主要问题在server_callBack函数里，当ret<0时会进行连接判断，这里判断之后没有把ret置为>0，导致server_callBack返回负值，继而误判为出错服务器主动断开连接。
2、还有就是这个延时再小都好，请务必加上，不然发出的数据像下图一样，看起来是数据连在了一起，导致一包数据过大。
========== server start ! ==========

server fd/7 : accept
server(fd/7) recv: Say hi~ from client(6307)
server(fd/7) recv: I am client(6307)
server webSocket_send err !!
accept close : 7 / -1266333165
server close !

========== client(6307) start ! ==========

webSocket_recv : warning !! recv buff too large !! (recv/10240)
client(6307) recv : Hi~ I am server
webSocket_recv : warning !! recv buff too large !! (recv/10240)
client(6307) recv : f��۳��۳�h����۳��ۮ@Vh0F
webSocket_recv : warning !! recv buff too large !! (recv/10240)
client(6307) recv : f��۳��۳�h����۳��ۮ@Vh0F
webSocket_recv : warning !! recv buff too large !! (recv/10240)
client(6307) recv : f��۳��۳�h����۳��ۮ@Vh0F
webSocket_recv : warning !! recv buff too large !! (recv/10240)

**Comment by Qianxunha** [comment]
@wexiangis 多谢博主

**Comment by Qianxunha** [comment]
@wexiangis 博主  make 出现了写警告，修改了下，没有警告了
server_main.c: 
1）145行，printf 打印多了个%d
2）162行，accept( )函数  第三个参数修改了类型   int  socAddrLen  -->  socklen_t  socAddrLen;
accept函数原型：int accept(int sockfd, struct sockaddr *addr, socklen_t *addrlen);
3）close 函数少了头文件 #include <unistd.h>
4） 61行，去掉未使用变量i
websocket_common.c：
1）缺少头文件 #include<pthread.h>
警告如下:
![20200506102342](https://user-images.githubusercontent.com/55270103/81133349-ebeeb980-8f83-11ea-98bc-1c87ac99132c.png)

**Comment by wexiangis** [comment]
1、你是对的<\捂脸>，建议已吸纳；
2、如果真要用到重要到项目去，建议自己重写这个服务器，毕竟早期只是配合验证API写的。代码还存在很多问题，像里面对已接入客户端的管理(添加和移除)，缺少互斥保护。

**Comment by Qianxunha** [comment]
@wexiangis 
1、好的谢谢博主
2、我是个小白，刚毕业，做嵌入式，借助这个websocket服务器是想 在服务器推送h.265裸流数据到浏览器中，js语言收流，将收集到的数据送入到ffmpeg库解码函数接口（使用WebAssembly技术，js语言调用C解码库），h.265裸流--》yuv数据 --》rgb数据，然后使用html5元素标签canvas 画布渲染在网页上，实现h.265裸流可以在web上直播监控。我们并发量不大，一万以下就行
3、之前我尝试过些websock服务器，后面写到websocket协议握手阶段，涉及到一些编码base64.c不会，加上工作项目时间紧，然后网上找到你的博客，看到你写比较好，就用这个了，后面加了些自己的代码进去，感觉还行
4、h.264方案OK，传统的推拉流方式
