### ISSUE TITLE
websocket服务器推送数据（图片，音视频数据）以二进制形式推送到浏览器中，js收数据，变成blob对象怎么处理

### ISSUE THREAD

**Issue by Qianxunha** [wexiangis/websocket_for_linux#3]
博主你好，可以解答下吗谢谢
在websocket服务器里推送音视频数据->浏览器中，js中收数据，数据变成了Blob对象，取不出数据，只取出数据大小，
Blob对象转为->ArrayBuffer->dataView,操控可视化数据，数据得到是一个个无符号整数了，转为十六进制又是错的数据，
![image](https://user-images.githubusercontent.com/55270103/82554449-86601700-9b98-11ea-8b64-136c97abdff1.png)

**Comment by Qianxunha** [comment]
![image](https://user-images.githubusercontent.com/55270103/82554540-bdcec380-9b98-11ea-8d48-f55f586f4699.png)

**Comment by wexiangis** [comment]
(PS: 不好意思，github没有邮箱通知我，我明明开了。。。[/再次捂脸]）
web、javascript我是不懂的，只能从传输部分给你建议：
1、视频数据要按帧发，取不出数据？就在客户端录下来播放看看，或下载个h264/265分析器比较下两边数据，确定数据传输没有问题
2、1080P时候的 I 帧数据会去到几百K，服务器发送的buff务必加大，保证一次发出；
3、针对你的客户端，会不会只能适配特定格式的h264/265格式，比如码率、每周期P帧数量会不会有特定要求。

**Comment by Qianxunha** [comment]
@wexiangis 谢谢博主
1.该问题我已经解决了，h264/h265编码的裸流已经渲染在网页上了。
2.传输部分建议已采纳，视频数据是按照一帧一帧推送到浏览器中，fps=25帧，网页刷的数据解码性能不够，只能达到23帧样子，ffmpeg解码，
